project_name: Asterisk ARI Proxy
builds:
   - env:
        - CGO_ENABLED=0
     goos:
        - windows
        - darwin
        - linux
     goarch:
        - amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^test:'

dockers:
   - image: cycoresystems/ari-proxy
     tag_templates:
        - "{{ .Tag }}"
        - "v{{ .Major }}"
        - "v{{ .Major }}.{{ .Minor }}"
        - latest
