language: go
go:
   - "1.12"
install:
   - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
   - go get -u github.com/goreleaser/goreleaser
script: make ci
services:
   - docker
deploy:
   - provider: script
     skip_cleanup: true
     script: bash ci_release.sh
     on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux

