project_name: Asterisk ARI Proxy
builds:
   - binary: ari-proxy
     env:
        - CGO_ENABLED=0
     goos:
        - windows
        - darwin
        - linux
     goarch:
        - amd64

archive:
   format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^test:'

dockers:
   - image_templates:
        - 'cycoresystems/ari-proxy:{{ .Tag }}'
        - 'cycoresystems/ari-proxy:v{{ .Major }}'
        - 'cycoresystems/ari-proxy:v{{ .Major }}.{{ .Minor }}'
        - 'cycoresystems/ari-proxy:latest'
